"""add user columns

Revision ID: 3e44ae42fad8
Revises: 53adfbb741fd
Create Date: 2021-12-23 09:13:16.517143

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = "3e44ae42fad8"
down_revision = "53adfbb741fd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column("activation_key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )
    op.add_column("user", sa.Column("key_expires", sa.DateTime(), nullable=False))
    op.add_column("user", sa.Column("verified", sa.Boolean(), nullable=True))
    op.add_column("user", sa.Column("premium_day_limit", sa.Integer(), nullable=True))
    op.create_index(
        op.f("ix_user_activation_key"), "user", ["activation_key"], unique=False
    )
    op.create_index(op.f("ix_user_key_expires"), "user", ["key_expires"], unique=False)
    op.create_index(
        op.f("ix_user_premium_day_limit"), "user", ["premium_day_limit"], unique=False
    )
    op.create_index(op.f("ix_user_verified"), "user", ["verified"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_verified"), table_name="user")
    op.drop_index(op.f("ix_user_premium_day_limit"), table_name="user")
    op.drop_index(op.f("ix_user_key_expires"), table_name="user")
    op.drop_index(op.f("ix_user_activation_key"), table_name="user")
    op.drop_column("user", "premium_day_limit")
    op.drop_column("user", "verified")
    op.drop_column("user", "key_expires")
    op.drop_column("user", "activation_key")
    # ### end Alembic commands ###
