"""add user columns

Revision ID: 53adfbb741fd
Revises: 9df03a0a6d32
Create Date: 2021-12-23 08:41:26.095731

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '53adfbb741fd'
down_revision = '9df03a0a6d32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('active', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('premium', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_user_active'), 'user', ['active'], unique=False)
    op.create_index(op.f('ix_user_premium'), 'user', ['premium'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_premium'), table_name='user')
    op.drop_index(op.f('ix_user_active'), table_name='user')
    op.drop_column('user', 'premium')
    op.drop_column('user', 'active')
    # ### end Alembic commands ###
