"""add private column

Revision ID: 9df03a0a6d32
Revises: c42802b681df
Create Date: 2021-12-23 08:36:43.552043

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '9df03a0a6d32'
down_revision = 'c42802b681df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tip', sa.Column('public', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_tip_public'), 'tip', ['public'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tip_public'), table_name='tip')
    op.drop_column('tip', 'public')
    # ### end Alembic commands ###
