"""Initial Migration

Revision ID: c42802b681df
Revises: 
Create Date: 2021-12-23 08:33:39.957512

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'c42802b681df'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('added', sa.DateTime(timezone=True), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=False)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_index(op.f('ix_user_password'), 'user', ['password'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=False)
    op.create_table('tip',
    sa.Column('added', sa.DateTime(timezone=True), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('background', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('theme', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tip_background'), 'tip', ['background'], unique=False)
    op.create_index(op.f('ix_tip_code'), 'tip', ['code'], unique=False)
    op.create_index(op.f('ix_tip_description'), 'tip', ['description'], unique=False)
    op.create_index(op.f('ix_tip_id'), 'tip', ['id'], unique=False)
    op.create_index(op.f('ix_tip_language'), 'tip', ['language'], unique=False)
    op.create_index(op.f('ix_tip_theme'), 'tip', ['theme'], unique=False)
    op.create_index(op.f('ix_tip_title'), 'tip', ['title'], unique=False)
    op.create_index(op.f('ix_tip_url'), 'tip', ['url'], unique=False)
    op.create_index(op.f('ix_tip_user_id'), 'tip', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tip_user_id'), table_name='tip')
    op.drop_index(op.f('ix_tip_url'), table_name='tip')
    op.drop_index(op.f('ix_tip_title'), table_name='tip')
    op.drop_index(op.f('ix_tip_theme'), table_name='tip')
    op.drop_index(op.f('ix_tip_language'), table_name='tip')
    op.drop_index(op.f('ix_tip_id'), table_name='tip')
    op.drop_index(op.f('ix_tip_description'), table_name='tip')
    op.drop_index(op.f('ix_tip_code'), table_name='tip')
    op.drop_index(op.f('ix_tip_background'), table_name='tip')
    op.drop_table('tip')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_password'), table_name='user')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
