"""add wt column

Revision ID: ed403b0ed346
Revises: 9736cdc8b5e9
Create Date: 2022-11-27 10:33:47.320197

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "ed403b0ed346"
down_revision = "9736cdc8b5e9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tip", sa.Column("wt", sqlmodel.sql.sqltypes.AutoString(), nullable=True)
    )
    op.alter_column("tip", "public", existing_type=sa.BOOLEAN(), nullable=False)
    op.drop_index("ix_tip_background", table_name="tip")
    op.drop_index("ix_tip_code", table_name="tip")
    op.drop_index("ix_tip_description", table_name="tip")
    op.drop_index("ix_tip_id", table_name="tip")
    op.drop_index("ix_tip_language", table_name="tip")
    op.drop_index("ix_tip_public", table_name="tip")
    op.drop_index("ix_tip_theme", table_name="tip")
    op.drop_index("ix_tip_title", table_name="tip")
    op.drop_index("ix_tip_url", table_name="tip")
    op.drop_index("ix_tip_user_id", table_name="tip")
    op.alter_column(
        "user", "activation_key", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "user", "key_expires", existing_type=postgresql.TIMESTAMP(), nullable=False
    )
    op.alter_column("user", "verified", existing_type=sa.BOOLEAN(), nullable=False)
    op.alter_column("user", "active", existing_type=sa.BOOLEAN(), nullable=False)
    op.alter_column("user", "premium", existing_type=sa.BOOLEAN(), nullable=False)
    op.alter_column(
        "user", "premium_day_limit", existing_type=sa.INTEGER(), nullable=False
    )
    op.drop_index("ix_user_activation_key", table_name="user")
    op.drop_index("ix_user_active", table_name="user")
    op.drop_index("ix_user_email", table_name="user")
    op.drop_index("ix_user_id", table_name="user")
    op.drop_index("ix_user_key_expires", table_name="user")
    op.drop_index("ix_user_password", table_name="user")
    op.drop_index("ix_user_premium", table_name="user")
    op.drop_index("ix_user_premium_day_limit", table_name="user")
    op.drop_index("ix_user_username", table_name="user")
    op.drop_index("ix_user_verified", table_name="user")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("ix_user_verified", "user", ["verified"], unique=False)
    op.create_index("ix_user_username", "user", ["username"], unique=False)
    op.create_index(
        "ix_user_premium_day_limit", "user", ["premium_day_limit"], unique=False
    )
    op.create_index("ix_user_premium", "user", ["premium"], unique=False)
    op.create_index("ix_user_password", "user", ["password"], unique=False)
    op.create_index("ix_user_key_expires", "user", ["key_expires"], unique=False)
    op.create_index("ix_user_id", "user", ["id"], unique=False)
    op.create_index("ix_user_email", "user", ["email"], unique=False)
    op.create_index("ix_user_active", "user", ["active"], unique=False)
    op.create_index("ix_user_activation_key", "user", ["activation_key"], unique=False)
    op.alter_column(
        "user", "premium_day_limit", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column("user", "premium", existing_type=sa.BOOLEAN(), nullable=True)
    op.alter_column("user", "active", existing_type=sa.BOOLEAN(), nullable=True)
    op.alter_column("user", "verified", existing_type=sa.BOOLEAN(), nullable=True)
    op.alter_column(
        "user", "key_expires", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    op.alter_column("user", "activation_key", existing_type=sa.VARCHAR(), nullable=True)
    op.create_index("ix_tip_user_id", "tip", ["user_id"], unique=False)
    op.create_index("ix_tip_url", "tip", ["url"], unique=False)
    op.create_index("ix_tip_title", "tip", ["title"], unique=False)
    op.create_index("ix_tip_theme", "tip", ["theme"], unique=False)
    op.create_index("ix_tip_public", "tip", ["public"], unique=False)
    op.create_index("ix_tip_language", "tip", ["language"], unique=False)
    op.create_index("ix_tip_id", "tip", ["id"], unique=False)
    op.create_index("ix_tip_description", "tip", ["description"], unique=False)
    op.create_index("ix_tip_code", "tip", ["code"], unique=False)
    op.create_index("ix_tip_background", "tip", ["background"], unique=False)
    op.alter_column("tip", "public", existing_type=sa.BOOLEAN(), nullable=True)
    op.drop_column("tip", "wt")
    # ### end Alembic commands ###
